all_keymaps = {
    'af': 'Afghanistan',
    'al': 'Albania',
    'am': 'Armenia',
    'ara': 'Arabic',
    'at': 'Austria',
    'au': 'Australia',
    'az': 'Azerbaijan',
    'ba': 'Bosnia and Herzegovina',
    'bd': 'Bangladesh',
    'be': 'Belgium',
    'bg': 'Bulgaria',
    'br': 'Brazil',
    'bt': 'Bhutan',
    'bw': 'Botswana',
    'by': 'Belarus',
    'ca': 'Canada',
    'cd': 'Democratic Republic of Congo',
    'ch': 'Switzerland',
    'cm': 'Cameroon',
    'cn': 'China',
    'cz': 'Czechia',
    'de': 'Germany',
    'dk': 'Denmark',
    'dz': 'Algeria',
    'ee': 'Estonia',
    'es': 'Spain',
    'et': 'Ethiopia',
    'fi': 'Finland',
    'fo': 'Faroe Islands',
    'fr': 'France',
    'gb': 'Great Britian',
    'ge': 'Georgia',
    'gh': 'Ghana',
    'gn': 'Guinea',
    'gr': 'Greece',
    'hr': 'Croatia',
    'hu': 'Hungary',
    'id': 'Indonesia',
    'ie': 'Ireland',
    'il': 'Israel',
    'in': 'India',
    'iq': 'Iraq',
    'ir': 'Iran',
    'is': 'Iceland',
    'it': 'Italy',
    'jp': 'Japan',
    'ke': 'Kenya',
    'kg': 'Kyrgyzstan',
    'kh': 'Cambodia',
    'kr': 'The Republic of Korea',
    'kz': 'Kazakhstan',
    'la': 'Laos',
    'lk': 'Sri Lanka',
    'lt': 'Lithuania',
    'la-latin1': 'Latin America',
    'lv': 'Lativa',
    'ma': 'Morocco',
    'md': 'Moldova',
    'me': 'Montenegro',
    'mk': 'Republic of North Macedonia',
    'ml': 'Mali',
    'mm': 'Myanmar',
    'mn': 'Mongolia',
    'mt': 'Malta',
    'mv': 'Maldives',
    'my': 'Malaysia',
    'ng': 'Nigeria',
    'nl': 'Netherlands',
    'no': 'Norway',
    'np': 'Nepal',
    'ph': 'Philippines',
    'pk': 'Pakistan',
    'pl': 'Poland',
    'pt': 'Portugal',
    'ro': 'Romania',
    'rs': 'Serbia',
    'ru': 'Russia',
    'se': 'Sweden',
    'si': 'Slovenia',
    'sk': 'Slovakia',
    'sn': 'Senegal',
    'sl': 'Sierra Leone',
    'sy': 'Syria',
    'tg': 'Togo',
    'th': 'Thailand',
    'tj': 'Tajikistan',
    'tm': 'Turkmenistan',
    'tr': 'Turkey',
    'tw': 'Taiwan',
    'tz': 'Tanzania',
    'ua': 'Ukraine',
    'us': 'United States of America',
    'uz': 'Uzbekistan',
    'vn': 'Vietnam',
    'za': 'South Africa'
}